apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-sm
  labels:
    name: backend-sm
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - interval: 10s
    scrapeTimeout: 10s
    port: http-server
    targetPort: 4000
    path: /metrics
