apiVersion: operators.coreos.com/v1
kind: OperatorGroup 
metadata: 
  name: operatorgroup 
  namespace: kube-system
spec: 
  targetNamespaces: 
  - kube-system 
--- 
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: grafana-operator 
  namespace: kube-system 
spec: 
  channel: alpha 
  name: grafana-operator 
  source: operatorhubio-catalog 
  sourceNamespace: olm