kind: PersistentVolume
apiVersion: v1
metadata:
  name: primary-pv
  labels:    
    name: postgres-helm-operator 
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: primary-pvc
  labels:
    name: postgres-helm-operator
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
