apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-helm-operator
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: primary
  selector:
    name: postgres-helm-operator