apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-helm-operator
  template:
    metadata:
      labels:
        name: postgres-helm-operator
    spec:
      containers:
      - name: primary
        image: postgres:12
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: contacts
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: primary-pvc
