apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-helm-operator  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-helm-operator
  template:
    metadata:
      labels:
        name: postgres-helm-operator
    spec:           
      containers:
      - name: primary
        image: registry.redhat.io/rhel8/postgresql-12
		imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
          - name: POSTGRESQL_USER
            value: primary
          - name: POSTGRESQL_PASSWORD
            value: admin123
          - name: POSTGRESQL_DATABASE
            value: pgdb            
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: primary-pvc